# Generated by Django 2.2.6 on 2019-10-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('numberOfPhotos', models.IntegerField()),
                ('tags', models.CharField(default='photo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pictureUrl', models.CharField(max_length=100)),
                ('pictureID', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('numberOfComments', models.IntegerField()),
                ('authorID', models.CharField(max_length=20)),
                ('topicID', models.ForeignKey(default='UNSPECIFIED', on_delete=django.db.models.deletion.CASCADE, to='hello.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('commentText', models.CharField(max_length=255)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('authorID', models.CharField(max_length=20)),
                ('pictureID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.Picture')),
            ],
        ),
    ]
