# Generated by Django 2.2.6 on 2019-12-18 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('thumbnailURL', models.CharField(max_length=100)),
                ('numberOfPhotos', models.IntegerField()),
                ('tags', models.CharField(default='photo', max_length=100)),
                ('authorID', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pictureUrl', models.CharField(max_length=100)),
                ('pictureID', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('numberOfComments', models.IntegerField()),
                ('authorUsername', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=100)),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topicID', models.ForeignKey(default='UNSPECIFIED', on_delete=django.db.models.deletion.CASCADE, to='hello.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('commentText', models.CharField(max_length=255)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('authorUsername', models.CharField(max_length=255)),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pictureID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.Picture')),
            ],
        ),
    ]
