# Generated by Django 2.2.6 on 2019-10-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pictureID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
