# Generated by Django 2.2.6 on 2019-10-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20191009_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='topicName',
            field=models.ForeignKey(default='UNSPECIFIED', on_delete=django.db.models.deletion.CASCADE, to='hello.Topic'),
        ),
    ]
