# Generated by Django 2.2.6 on 2019-12-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20191113_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='authorUsername',
            field=models.CharField(default='defaultUsername', max_length=255),
            preserve_default=False,
        ),
    ]
