# Generated by Django 2.2.6 on 2019-10-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_picture_topicname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pictureID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.Picture'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
